// <auto-generated />
using System;
using LCMDB.BD.Contextos.LCMDB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LCMDB.BD.Migrations
{
    [DbContext(typeof(CMDBContexto))]
    [Migration("20201201042046_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("inv")
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("LCMDB.BD.Contextos.LCMDB.Modelos.v1_0.SegmentoRed", b =>
                {
                    b.Property<int>("IdSegmento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("IpRed")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MascaraSegmento")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.HasKey("IdSegmento");

                    b.ToTable("Cnf_SegmentoRed");
                });

            modelBuilder.Entity("LCMDB.BD.Contextos.LCMDB.Modelos.v1_0.Servidor", b =>
                {
                    b.Property<int>("IdServidor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("IP")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<string>("NombreServidor")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdServidor");

                    b.ToTable("Inv_Servidores");
                });
#pragma warning restore 612, 618
        }
    }
}
